version: '3.7'

services:
    pgsql:
        image: postgres:12.1-alpine
        environment:
            - TZ=Europe/Minsk
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        command:  postgres -c listen_addresses=*
        volumes:
            - pgdata_12_1:/var/lib/postgresql/data
        ports:
            - ${DB_PORT}:5432

    php-fpm:
        build:
            context: .
            dockerfile: docker/php/dev/fpm.Dockerfile
        depends_on:
            - pgsql
        volumes:
            - ./:/var/www/app.loc
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        environment:
            XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST} remote_port=${XDEBUG_REMOTE_PORT}
            PHP_IDE_CONFIG: serverName=${IDE_SERVER_NAME}

    php-cli:
        build:
            context: .
            dockerfile: docker/php/dev/cli.Dockerfile
        depends_on:
            - pgsql
        volumes:
            - ./:/var/www/app.loc
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        environment:
            XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST} remote_port=${XDEBUG_REMOTE_PORT}
            PHP_IDE_CONFIG: serverName=${IDE_SERVER_NAME}
        tty: true

    nginx:
        image: nginx:1.17-alpine
        volumes:
            - ./docker/nginx/dev/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/app.loc
        depends_on:
            - php-fpm
        ports:
          - ${NGINX_PORT}:8001

volumes:
    pgdata_12_1:
